### ISSUE TITLE
URL tidak ditemukan

### ISSUE THREAD

**Issue by hairil2912** [morizbebenk/php-bpjs-rest#1]
![image](https://user-images.githubusercontent.com/76684548/147588486-5b512135-c718-48b6-948f-9f53849cc391.png)

**Comment by hairil2912** [comment]
izin bang

**Comment by morizbebenk** [comment]
![Screenshot 2021-12-29 103728](https://user-images.githubusercontent.com/18350325/147625145-e09be143-ab25-47af-a7e4-89487f891634.png)

Saya coba bisa kok, coba di cek lagi consid, secret dan user_key nya sudah sesuai atau belum.
Jika sudah sesuai tapi masih belum bisa, coba cek di bagian Network / Jaringan, isi response nya apa?

**Comment by morizbebenk** [comment]
Issue ditutup karena tidak ada aktivitas.
